### ISSUE TITLE
stack-blitz starter for vite-elm ?

### ISSUE THREAD

**Issue by clojj** [lindsaykwardell/vite-elm-template#5]
Hi !

would it be possible to contribute a vite-elm starter here ?
https://stackblitz.com/?starters=vite

It'd be a nice way to push Elm...

**Comment by lindsaykwardell** [comment]
Unfortunately Elm does not work in StackBlitz. This is because the Elm compiler is built in Haskell, which does not currently run in web containers.

Currently the best way to work with Elm and Vite in a web-based inteface is GitPod, since it gives you a full Linux environment and the tooling works as expected.

I've brought this issue up to StackBlitz in the past and they are definitely aware of it, but since Haskell/C is not their main focus it hasn't been prioritized yet.
